name             'promet_php'
maintainer       'Promet Solutions, Inc'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures promet_php'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.1'
depends		 'apache2'
depends		 'apt'
depends		 'php', '= 1.3.10'
