name             'promet_php'
maintainer       'Promet Solutions, Inc'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures promet_php'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.4.3'
depends		 'apache2'
depends		 'nginx'
depends		 'apt'
depends		 'ark'
depends		 'build-essential'
depends		 'yum'
depends		 'yum-epel'
